name: Deploy TrendTrove
on:
  push:
    branches: [ main ]
    
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_MEDUSA_BACKEND_URL: 'https://trendtrove-app-q4wqs.ondigitalocean.app'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build
        env:
          NEXT_PUBLIC_MEDUSA_BACKEND_URL: 'https://trendtrove-app-q4wqs.ondigitalocean.app'
      - name: List directories (for debugging)
        run: ls -la
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: trendtrove-frontend
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'out'